version: '3.0'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    website-admin:
        image: ngapham0705/website-admin:latest
        container_name: website-admin
        ports:
            - 4200:4200
        environment:
            - VIRTUAL_HOST=admin.huyenduc.click
            - VIRTUAL_PORT=4200