version: '3.0'

services:
    website-admin:
        image: ngapham0705/website-admin:latest
        container_name: website-admin
        ports:
            - 4200:4200
        volumes:
            - "/app/node_modules"
            - ".:/app"