version: '3.0'

services:
    website-admin:
        image: ngapham0705/website-admin:latest
        container_name: website-admin
        networks:
            - website-network
        ports:
            - 4200:4200
        environment:
            - VIRTUAL_HOST=admin.huyenduc.click
networks:
  website-network:
    external: true
    name: website-network