version: '3.0'

services:
    website-admin:
        image: ngapham0705/website-admin:latest
        container_name: website-admin
        ports:
            - 4200:4200
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.mycontainer.rule=Host(`admin.huyenduc.click`)"
            - "traefik.http.routers.mycontainer.entrypoints=http"