name: Angaular Build

on:
  push:
    branches-ignore:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
        - uses: actions/checkout@v3
        - name: Setup Angular
          uses: actions/setup-node@v3
          with:
            node-version: 16

        - name: Install dependencies
          run: npm install

        - name: Build
          run: npm run build:prod